name: Mi primer workflow
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    name: Mi primer job
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar deploy
        uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: |
          npm i
          npm run-script build
      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@releases/v3                             
        with:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages  
          FOLDER: main/prueba-actions
      - name: Deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project default
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  